class ApiService {
  constructor() {
    // Use production server from swagger.json
    this.baseURL = 'https://edushelf-re0u.onrender.com/api';
    this.token = null;
  }

  setToken(token) {
    this.token = token;
  }

  async request(endpoint, options = {}) {
    const url = `${this.baseURL}${endpoint}`;
    const config = {
      headers: {
        'Content-Type': 'application/json',
        ...(this.token && { Authorization: `Bearer ${this.token}` }),
      },
      ...options,
    };

    try {
      const response = await fetch(url, config);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      return await response.json();
    } catch (error) {
      console.error('API request failed:', error);
      throw error;
    }
  }

  // Auth endpoints - matching swagger.json paths
  async register(userData) {
    return this.request('/auth/register', {
      method: 'POST',
      body: JSON.stringify(userData),
    });
  }

  async login(credentials) {
    return this.request('/auth/login', {
      method: 'POST',
      body: JSON.stringify(credentials),
    });
  }

  // User endpoints - matching swagger.json paths
  async getUserProfile() {
    return this.request('/users/profile');
  }

  async updateUserProfile(data) {
    return this.request('/users/profile', {
      method: 'PUT',
      body: JSON.stringify(data),
    });
  }

  // Content generation endpoints - matching swagger documentation
  async generateContent(data) {
    return this.request('/content/generate', {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  // Progress endpoints - matching swagger documentation
  async getProgress() {
    return this.request('/progress');
  }

  async updateProgress(data) {
    return this.request('/progress', {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  // Leaderboard endpoints - matching swagger documentation
  async getLeaderboard() {
    return this.request('/leaderboard');
  }

  // AI Chat endpoints - matching swagger documentation
  async chatWithAI(data) {
    return this.request('/ai/chat', {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  // JAMB Tutor endpoint
  async chatWithJAMBTutor(data) {
    return this.request('/ai/jamb-tutor', {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  // WAEC Tutor endpoint
  async chatWithWAECTutor(data) {
    return this.request('/ai/waec-tutor', {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  // Materials endpoints
  async convertMaterial(materialData) {
    // For demo purposes, simulate the conversion with mock data
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve({
          success: true,
          conversion: {
            id: Date.now(),
            original_filename: materialData.file.name,
            created_at: new Date().toISOString(),
            interests: materialData.interests,
            learning_style: materialData.learningStyle,
            difficulty: materialData.difficulty
          },
          personalizedContent: `# 📚 Personalized Study Material: ${materialData.file.name}

## 🎯 Tailored for Your Learning Style: ${materialData.learningStyle}

### Key Concepts Simplified

This material has been transformed to match your interests in **${materialData.interests}** and adapted for ${materialData.learningStyle} learners at ${materialData.difficulty} level.

#### Main Topics Covered:

1. **Core Concept 1**: Explained using ${materialData.interests} analogies
   - Think of this like your favorite sport/hobby
   - Step-by-step breakdown for ${materialData.learningStyle} learners
   - Real-world applications you can relate to

2. **Core Concept 2**: Simplified for ${materialData.difficulty} understanding
   - Visual diagrams and examples (for Visual learners)
   - Interactive exercises (for Kinesthetic learners)
   - Audio mnemonics (for Auditory learners)
   - Structured notes (for Reading/Writing learners)

3. **Practice Applications**:
   - Hands-on examples using ${materialData.interests}
   - Memory tricks and shortcuts
   - Common mistakes to avoid

### 🧠 Memory Aids
- **Acronym**: Remember key points with easy mnemonics
- **Visual Cues**: Connect concepts to things you love
- **Practice Questions**: Test your understanding

### 📝 Summary
This personalized version breaks down complex academic content into digestible, relatable pieces that match how you learn best. The examples use your interests in ${materialData.interests} to make abstract concepts concrete and memorable.

**Next Steps**: 
- Review the key concepts
- Practice with the examples
- Discuss with AI tutor for deeper understanding

*Generated by Lumina's Smart Material Converter using Gemini 2.5 Flash AI*`
        });
      }, 2000); // 2 second delay to simulate processing
    });
  }

  async getMaterialHistory() {
    return {
      conversions: [
        {
          id: 1,
          original_filename: 'Advanced_Calculus_Notes.pdf',
          learning_style: 'Visual',
          difficulty: 'Intermediate',
          interests: 'technology, gaming',
          created_at: new Date(Date.now() - 86400000).toISOString()
        },
        {
          id: 2,
          original_filename: 'Organic_Chemistry_Slides.pptx',
          learning_style: 'Kinesthetic',
          difficulty: 'Advanced',
          interests: 'sports, music',
          created_at: new Date(Date.now() - 172800000).toISOString()
        }
      ]
    };
  }

  async getMaterialConversion(conversionId) {
    return {
      conversion: {
        id: conversionId,
        original_filename: 'Sample_Material.pdf',
        personalized_content: 'This is a sample personalized material content...',
        learning_style: 'Visual',
        difficulty: 'Intermediate',
        interests: 'technology, sports',
        created_at: new Date().toISOString()
      }
    };
  }
}

export default new ApiService();